---
title: "OIA Averaging"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

# Libraries

```{r load_libraries_specific, include = FALSE}
library(patchwork)
library(ggalluvial)
library(marelac)
library(ggdist)
library(kableExtra)
library(khroma)
library(ggh4x)
library(ggpattern)
library(colorspace)
library(stars)
library(seacarb)
```

```{r select_basinmask_5}

basinmask <- basinmask %>% 
  filter(MLR_basins == "5") %>% 
  select(lon, lat, basin)

```


```{r define_paths_to_access_eMLR_files, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste0(path_root, "/observations/")

path_preprocessing    <-
  paste0(path_observations, "preprocessing/")


path_preprocessing_model    <-
  paste0(path_root, "/model/preprocessing/")

path_out <-   paste0(path_observations, "output_publication/")
path_OIA <-   "/nfs/kryo/work/jenmueller/ocean_interior_acidification/"


```

# Read data

```{r read_OIA_data}


acidification_trend <-
  read_csv(paste0(path_OIA, "OIA_all.csv"))

# read_csv(paste0(path_OIA, "OIA_all.csv"))

# acidification_trend %>%
#   filter(Version_ID_group == "Standard case",
#          MLR_basins == "3") %>%
#   write_csv(paste0(path_OIA, "OIA_standard_case.csv"))


```

# Uncertainty determination

```{r reference_dcant_reconstructions}

MLR_basins_reference <- unique(acidification_trend$MLR_basins)[1]

MLR_basins_all <- unique(acidification_trend$MLR_basins)

MLR_basins_uncertainty <-
  MLR_basins_all[!MLR_basins_all %in% MLR_basins_reference]



Version_ID_group_reference <-
  unique(acidification_trend$Version_ID_group)[1]
Version_ID_group_all <-
  unique(acidification_trend$Version_ID_group)

Version_ID_group_uncertainty <-
  Version_ID_group_all[Version_ID_group_all != Version_ID_group_reference]

```



```{r uncertainty_determination}

# df <- acidification_zonal

additive_uncertainty <- function(df){
  
  # df <- df %>%
  #   filter(tref %in% c("2004", "2014")) %>%
  #   select(-c(gamma_mean:hyd_ion_mean)) %>% 
  #   select(-contains(c("_sd", "_total_mean")))

  df_regional_uncertainty <-
    df %>%
    filter(MLR_basins != MLR_basins_reference,
           Version_ID_group == Version_ID_group_reference) %>% 
    select(-Version_ID_group) %>% 
    pivot_wider(names_from = MLR_basins,
                values_from = contains("_interval_mean"),
                names_sep = "-") %>%
    pivot_longer(all_of(contains(MLR_basins_uncertainty)),
                 names_to = c("variable","MLR_basins"),
                 names_sep = "-",
                 values_to = "value")
  
  df_regional_reference <-
    df %>%
    filter(MLR_basins == MLR_basins_reference,
           Version_ID_group == Version_ID_group_reference) %>% 
    select(-c(MLR_basins, Version_ID_group)) %>% 
    pivot_longer(contains("_interval_mean"),
                 names_to = c("variable"),
                 values_to = MLR_basins_reference)
  
  df_regional <-
    full_join(df_regional_reference, df_regional_uncertainty)
  
  df_regional <-
    df_regional %>%
    mutate(delta_value = value-!!sym(MLR_basins_reference)) %>%
    select(-c(all_of(MLR_basins_reference), MLR_basins, value))

  df_regional_stat <-
    df_regional %>%
    group_by(across(-delta_value)) %>%
    summarise(sd = mean(abs(delta_value))) %>%
    ungroup()


  df_configuration_uncertainty <-
    df %>%
    filter(MLR_basins == MLR_basins_reference,
           Version_ID_group %in% Version_ID_group_uncertainty) %>% 
    select(-MLR_basins) %>% 
    pivot_wider(names_from = Version_ID_group,
                values_from = contains("_interval_mean"),
                names_sep = "-") %>%
   pivot_longer(all_of(contains(Version_ID_group_uncertainty)),
                 names_to = c("variable","Version_ID_group"),
                 names_sep = "-",
                 values_to = "value")

  
  df <-
    df %>%
    filter(MLR_basins == MLR_basins_reference,
           Version_ID_group == Version_ID_group_reference) %>% 
    select(-c(Version_ID_group, MLR_basins)) %>% 
    pivot_longer(contains("_interval_mean"),
                 names_to = c("variable"),
                 values_to = Version_ID_group_reference)

  df_configuration <-
    full_join(df, df_configuration_uncertainty) 
  
  df_configuration <- df_configuration %>% 
    mutate(delta_value = value-!!sym(Version_ID_group_reference))
  
  
  df_configuration <-
    df_configuration %>%
    rename(sd = delta_value) %>%
    select(-c(value, all_of(Version_ID_group_reference)))
  
  df_factorial <-
    bind_rows(
      df_regional_stat %>%
        mutate(Version_ID_group = "Regional clustering"),
      df_configuration
    )

  df_factorial_stat <-
    df_factorial %>%
    select(-Version_ID_group) %>%
    group_by(across(-sd)) %>%
    summarise(sd = sqrt(sum(sd ^ 2, na.rm = TRUE))) %>%
    ungroup()

  df_stat <-
    full_join(
      df_factorial_stat,
      df %>%
        rename(std_case = all_of(Version_ID_group_reference))
    )

  df_stat <- df_stat %>%
    mutate(
      signif_single = if_else(abs(std_case) >= sd,
                              1,
                              0),
      signif_double = if_else(abs(std_case) >= sd * 2,
                              1,
                              0)
    )

  df_stat_delta <-
    df_stat %>%
    select(-starts_with("signif_")) %>%
    arrange(tref) %>%
    group_by(across(-c(tref, sd, std_case))) %>%
    mutate(
      delta_value = std_case - lag(std_case),
      RSS = sqrt(sd ^ 2 + lag(sd ^ 2)),
      signif_single = if_else(abs(delta_value) >= RSS,
                              1,
                              0),
      signif_double = if_else(abs(delta_value) >= RSS * 2,
                              1,
                              0)
    ) %>%
    ungroup() %>%
    drop_na()


df_out <- list(df_stat, df_factorial, df_stat_delta)

return(df_out)

}


```


# Results

## Maps

```{r layered_maps, eval=FALSE}


acidification_layer <- acidification_trend %>%
  mutate(depth_layer = cut(
    depth,
    c(0, 50, 100, 250, 500, 1000, 1500, 2000, 3000),
    include.lowest = TRUE
  )) %>%
  drop_na() %>%
  select(c(lat, lon, depth_layer, tref), where(is.numeric)) %>%
  fgroup_by(lat, lon, depth_layer, tref) %>% {
    add_vars(
      fgroup_vars(., "unique"),
      fmean(., keep.group_vars = FALSE) %>% add_stub(pre = FALSE, "_mean"),
      fsd(., keep.group_vars = FALSE) %>% add_stub(pre = FALSE, "_sd")
    )
  }

acidification_layer %>% 
  filter(depth_layer %in% unique(acidification_layer$depth_layer)[c(1,5)],
         tref != 1800) %>% 
  ggplot(aes(lon, lat, fill = CO3_delta_total_mean)) +
  geom_raster() +
  scale_fill_viridis_c(direction = -1) +
  facet_grid(tref ~ depth_layer) +
  coord_quickmap()

acidification_layer %>% 
  filter(depth_layer %in% unique(acidification_layer$depth_layer)[c(1,5)],
         tref != 1800) %>% 
  ggplot(aes(lon, lat, fill = CO3_delta_interval_mean)) +
  geom_raster() +
  scale_fill_viridis_c(direction = -1) +
  facet_grid(tref ~ depth_layer) +
  coord_quickmap()

acidification_layer %>% 
  filter(depth_layer %in% unique(acidification_layer$depth_layer)[c(1,5)],
         tref != 1800) %>% 
  ggplot(aes(lon, lat, fill = pH_delta_total_mean)) +
  geom_raster() +
  scale_fill_viridis_c(direction = -1) +
  facet_grid(tref ~ depth_layer) +
  coord_quickmap()

```


## Zonal sections

```{r zonal_mean_sections}


acidification_zonal <- acidification_trend %>%
  group_by(tref, Version_ID_group, MLR_basins) %>%
  nest() %>%
  mutate(zonal = map(.x = data, ~m_zonal_mean_sd(.x))) %>%
  select(-data) %>%
  unnest(zonal) %>% 
  ungroup()

acidification_zonal_reference <- acidification_zonal %>%
  filter(
    Version_ID_group == Version_ID_group_reference,
    MLR_basins == MLR_basins_reference
  )

pdf(here::here("output/zonal_sections_total_changes.pdf"),
    width = 8,
    height = 4)

acidification_zonal_reference %>%
  filter(tref != 1800) %>%
  select(tref:basin_AIP, contains("_delta_total_mean")) %>%
  pivot_longer(contains("_delta_total_mean"),
               names_to = "variable",
               values_to = "value") %>%
  mutate(variable = str_remove(variable, "_delta_total_mean")) %>%
  group_by(variable) %>%
  group_split() %>%
  # head(2) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "value",
      legend_title = .x$variable,
      plot_slabs = "n",
      breaks = NULL,
      title_text = "Total change since 1800",
      subtitle_text = NULL
    ) +
      facet_grid(basin_AIP ~ tref)
  )

dev.off()

pdf(here::here("output/zonal_sections_incremental_changes_all.pdf"),
    width = 8,
    height = 4)

acidification_zonal_reference %>%
  filter(tref != 1800) %>%
  select(tref:basin_AIP, contains("_delta_interval_mean")) %>%
  pivot_longer(contains("_delta_interval_mean"),
               names_to = "variable",
               values_to = "value") %>%
  mutate(variable = str_remove(variable, "_delta_interval_mean")) %>%
  group_by(variable) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "value",
      legend_title = .x$variable,
      plot_slabs = "n",
      breaks = NULL,
      title_text = "Incremental change from previous estimate",
      subtitle_text = NULL
    ) +
      facet_grid(basin_AIP ~ tref)
  )

dev.off()

pdf(here::here("output/zonal_sections_incremental_changes_post_1994.pdf"),
    width = 6,
    height = 4)

acidification_zonal_reference %>%
  filter(tref %in% c(2004, 2014)) %>%
  select(tref:basin_AIP, contains("_delta_interval_mean")) %>%
  pivot_longer(contains("_delta_interval_mean"),
               names_to = "variable",
               values_to = "value") %>%
  mutate(variable = str_remove(variable, "_delta_interval_mean")) %>%
  group_by(variable) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "value",
      legend_title = .x$variable,
      plot_slabs = "n",
      breaks = NULL,
      title_text = "Incremental change from previous estimate",
      subtitle_text = NULL
    ) +
      facet_grid(basin_AIP ~ tref)
  )

dev.off()

pdf(here::here("output/zonal_sections_absolute_levels.pdf"),
    width = 10,
    height = 4)

acidification_zonal_reference %>%
  # filter(tref %in% c(2004, 2014)) %>%
  select(tref:hyd_ion_mean) %>%
  pivot_longer(contains("_mean"),
               names_to = "variable",
               values_to = "value") %>%
  mutate(variable = str_remove(variable, "_mean")) %>%
  group_by(variable) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "value",
      legend_title = .x$variable,
      plot_slabs = "n",
      breaks = NULL,
      title_text = "Absolute values",
      subtitle_text = NULL
    ) +
      facet_grid(basin_AIP ~ tref)
  )

dev.off()


```


```{r zonal_uncertainty}

acidification_zonal_uncertainty <-
  acidification_zonal %>%
  select(MLR_basins:basin_AIP,
         contains("_delta_interval"),
         -contains("_sd")) %>%
  filter(tref %in% c(2004, 2014)) %>% 
  mutate(lat = as.numeric(as.character(cut(
    lat, seq(-90, 90, 10), seq(-85, 85, 10)
  ))),
  depth = as.numeric(as.character(cut(
    depth,
    c(seq(0, 500, 100), seq(1000, 10000, 500)),
    c(seq(50, 450, 100), seq(750, 10000, 500)),
    right = FALSE
  )))
  ) %>%
  group_by(across(-contains("_delta_interval"))) %>%
  summarise(across(everything(), mean)) %>%
  ungroup()


acidification_zonal_uncertainty <- additive_uncertainty(acidification_zonal_uncertainty)

delta_acidification_zonal_uncertainty <-
  acidification_zonal_uncertainty[[3]]
acidification_zonal_uncertainty <-
  acidification_zonal_uncertainty[[1]]


pdf(here::here("output/zonal_sections_incremental_changes_all_uncertainty_std_case.pdf"),
    width = 6,
    height = 4)

acidification_zonal_uncertainty %>%
  mutate(variable = str_remove(variable, "_delta_interval_mean")) %>%
  group_by(variable) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "std_case",
      legend_title = .x$variable,
      plot_slabs = "n",
      breaks = NULL,
      title_text = "Incremental change from previous estimate",
      subtitle_text = NULL
    ) +
        geom_point(
          data = .x %>% filter(signif_single == 0),
          aes(lat, depth),
          shape = 20,
          size = 1,
          col = "grey"
        ) +
        geom_point(
          data = .x %>% filter(signif_double == 0),
          aes(lat, depth),
          shape = 20,
          size = 0.1,
          col = "grey"
        ) +
      facet_grid(basin_AIP ~ tref)
  )

dev.off()


pdf(here::here("output/zonal_sections_incremental_changes_all_uncertainty_sd.pdf"),
    width = 6,
    height = 4)

acidification_zonal_uncertainty %>%
  mutate(variable = str_remove(variable, "_delta_interval_mean")) %>%
  group_by(variable) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "sd",
      legend_title = .x$variable,
      plot_slabs = "n",
      breaks = NULL,
      title_text = "Uncertainty estimate",
      subtitle_text = "Incremental change from previous estimate"
    ) +
      facet_grid(basin_AIP ~ tref)
  )

dev.off()



pdf(here::here("output/delta_zonal_sections_incremental_changes_all_uncertainty_std_case.pdf"),
    width = 6,
    height = 6)

delta_acidification_zonal_uncertainty %>%
  mutate(variable = str_remove(variable, "_delta_interval_mean")) %>%
  group_by(variable) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "delta_value",
      legend_title = .x$variable,
      plot_slabs = "n",
      col = "div",
      breaks = NULL,
      title_text = "Decadal differences",
      subtitle_text = "Incremental change from previous estimate"
    ) +
        geom_point(
          data = .x %>% filter(signif_single == 0),
          aes(lat, depth),
          shape = 20,
          size = 1,
          col = "grey"
        ) +
        geom_point(
          data = .x %>% filter(signif_double == 0),
          aes(lat, depth),
          shape = 20,
          size = 0.1,
          col = "grey"
        ) +
      facet_grid(basin_AIP ~ .)
  )

dev.off()




```


## Global sections


```{r global_section}

acidification_global_section <- acidification_trend %>%
  group_by(tref, MLR_basins, Version_ID_group) %>%
  nest() %>%
  mutate(zonal = map(.x = data, ~m_section_global_mean_sd(.x))) %>%
  select(-data) %>%
  unnest(zonal) %>% 
  ungroup()


acidification_global_section_incremental <-
  acidification_global_section %>%
  select(MLR_basins:band, dist,
         contains("_delta_interval"),
         -contains("_sd")) %>%
  filter(tref %in% c(2004, 2014))

acidification_global_section_uncertainty <-
  acidification_global_section_incremental %>%
  mutate(dist = as.numeric(as.character(cut(
    dist, seq(0, 50, 1), seq(0.5, 49.5, 1)
  ))),
  depth = as.numeric(as.character(cut(
    depth,
    c(seq(0, 500, 100), seq(1000, 10000, 500)),
    c(seq(50, 450, 100), seq(750, 10000, 500)),
    right = FALSE
  )))) %>%
  group_by(across(-contains("_delta_interval"))) %>%
  summarise(across(everything(), mean)) %>%
  ungroup()




acidification_global_section_uncertainty <-
  additive_uncertainty(acidification_global_section_uncertainty)

delta_acidification_global_section_uncertainty <- acidification_global_section_uncertainty[[3]]
acidification_global_section_uncertainty_contributions <- acidification_global_section_uncertainty[[2]]
acidification_global_section_uncertainty <- acidification_global_section_uncertainty[[1]]



acidification_global_section_uncertainty %>% 
  filter(tref == "2014",
         variable == "CO3_delta_interval_mean") %>% 
  p_section_global(
    var = "std_case",
    plot_slabs = "n",
    title_text = NULL,
    subtitle_text = NULL,
    col = "div"
  )

p_section_global(
  df = acidification_global_section %>%
    filter(tref == "2014",
           MLR_basins == MLR_basins_reference,
           Version_ID_group == Version_ID_group_reference),
  var = "pH_mean",
  plot_slabs = "n"
)

acidification_global_section_incremental <-
  acidification_global_section_incremental %>%
  filter(MLR_basins == MLR_basins_reference,
         Version_ID_group == Version_ID_group_reference) %>%
  select(-c(MLR_basins, Version_ID_group)) %>%
  pivot_longer(contains("_delta_interval"),
               names_to = "variable",
               values_to = "delta_interval") %>%
  mutate(variable = str_remove(variable, "_delta_interval_mean"))


variables_incremental <- 
  acidification_global_section_incremental %>% 
  distinct(variable) %>% 
  pull()


acidification_global_section_uncertainty <-
  acidification_global_section_uncertainty %>%
  mutate(variable = str_remove(variable, "_delta_interval_mean"))

delta_acidification_global_section_uncertainty <-
  delta_acidification_global_section_uncertainty %>%
  mutate(variable = str_remove(variable, "_delta_interval_mean"))



pdf(
  here::here("output/global_sections_incremental_changes.pdf"),
  width = 10,
  height = 12
)


for (i_var in variables_incremental) {
  # i_var <- variables_incremental[1]
  
  i_acidification_global_section_incremental <-
    acidification_global_section_incremental %>%
    filter(variable == i_var)
  
  low <- i_acidification_global_section_incremental %>%
    filter(!is.na(delta_interval)) %>%
    pull(delta_interval) %>%
    quantile(c(.02), names = FALSE)
  
  high <- i_acidification_global_section_incremental %>%
    filter(!is.na(delta_interval)) %>%
    pull(delta_interval) %>%
    quantile(c(.98), names = FALSE)
  
  breaks <- c(-Inf, seq(low, high, length.out = 10), Inf)
  
  p_global_section_dec1 <-
    acidification_global_section_incremental %>%
    filter(tref == 2004,
           variable == i_var) %>%
    p_section_global(
      var = "delta_interval",
      legend_title = i_var,
      title_text = "A   1994 - 2004",
      df_uncertainty = acidification_global_section_uncertainty %>%
        filter(tref == 2004,
               variable == i_var),
      breaks = breaks,
      # df_penetration = dcant_global_section_all_penetration %>%
      #   filter(data_source == "obs",
      #          period %in% "1994 - 2004"),
      col_uncertainty = "grey",
      subtitle_text = NULL,
      plot_slabs = "n"
    ) &
    theme(axis.title.x = element_blank(),
          axis.text.x.bottom = element_blank())
  
  p_global_section_dec2 <-
    acidification_global_section_incremental %>%
    filter(tref == 2014,
           variable == i_var) %>%
    p_section_global(
      var = "delta_interval",
      title_text = "B   2004 - 2014",
      subtitle_text = NULL,
      plot_slabs = "n",
      df_uncertainty = acidification_global_section_uncertainty %>%
        filter(tref == 2014,
               variable == i_var),
      col_uncertainty = "grey",
      breaks = breaks
      # df_penetration = dcant_global_section_all_penetration %>%
      #   filter(data_source == "obs",
      #          period %in% "2004 - 2014")
    ) &
    theme(legend.position = "none")
  
  p_global_section_offset <-
    acidification_global_section_incremental %>%
    filter(variable == i_var) %>%
    arrange(depth, dist) %>%
    select(depth, dist, tref, delta_interval) %>%
    drop_na() %>%
    pivot_wider(names_from = tref,
                values_from = delta_interval) %>%
    mutate(delta_delta_interval = `2014` - `2004`) %>%
    p_section_global(
      var = "delta_delta_interval",
      legend_title = paste("delta\n", i_var),
      df_uncertainty = delta_acidification_global_section_uncertainty %>%
        filter(variable == i_var),
      plot_slabs = "n",
      col = "div",
      title_text = "C   Decadal difference",
      subtitle_text = NULL
    )
  
  print(
    wrap_plots(
      p_global_section_dec1,
      p_global_section_dec2 &
        theme(axis.title.x = element_blank(),
              axis.text.x = element_blank()),
      p_global_section_offset &
        theme(axis.text.x.top = element_blank()),
      ncol = 1
    )
  )
  
}

dev.off()


```

## Profiles

```{r mean_profiles}

basinmask <- basinmask %>% 
    mutate(area = earth_surf(lat, lon))

acidification_profiles <-
  full_join(basinmask,
            acidification_trend %>%
              select(-c(basin_AIP))) %>%
  drop_na() %>%
  relocate(tref, MLR_basins, Version_ID_group)

acidification_profiles <- acidification_profiles %>% 
  mutate(across(gamma:hyd_ion_delta_interval,
                ~ . * area))

acidification_profiles_regional <- acidification_profiles %>%
  group_by(tref, basin, depth, MLR_basins, Version_ID_group) %>%
  summarise(across(gamma:hyd_ion_delta_interval,
                   ~ sum(.) / sum(area))) %>%
  ungroup()

acidification_profiles_global <- acidification_profiles %>%
  mutate(basin = "Global") %>% 
  group_by(tref, basin, depth, MLR_basins, Version_ID_group) %>%
  summarise(across(gamma:hyd_ion_delta_interval,
                   ~ sum(.) / sum(area))) %>%
  ungroup()

  
acidification_profiles <-
  bind_rows(acidification_profiles_global,
            acidification_profiles_regional)
  
rm(acidification_profiles_regional,
   acidification_profiles_global)

acidification_profiles %>%
  distinct(basin)

acidification_profiles <- acidification_profiles %>%
  mutate(
    basin = str_replace(basin,
                        "_",
                        ". "),
    basin = fct_relevel(
      basin,
      "Global",
      "N. Pacific",
      "N. Atlantic",
      "Indian",
      "S. Pacific",
      "S. Atlantic"
    )
  )

acidification_profiles <- acidification_profiles %>%
  mutate(tref = as.factor(tref))
  
acidification_profiles %>%
  select(tref,
         basin,
         depth,
         MLR_basins,
         Version_ID_group,
         contains("_delta_total")) %>%
  pivot_longer(contains("_delta_total"),
               names_to = "variable",
               values_to = "delta_total") %>%
  filter(tref != 1800,
         depth <= 3000,
         MLR_basins == MLR_basins_reference,
         Version_ID_group == Version_ID_group_reference) %>%
  mutate(variable = str_remove(variable, "_delta_total")) %>% 
  ggplot(aes(
    delta_total,
    depth,
    col = tref,
    group = interaction(tref, MLR_basins, Version_ID_group)
  )) +
  geom_vline(xintercept = 0) +
  geom_path() +
  scale_color_brewer(palette = "Set1", direction = -1) +
  labs(y = "Depth (m)",
       title = "Total change since 1800")+
  scale_y_continuous(trans = trans_reverser("sqrt"),
                     breaks = c(0, 100, 500, seq(1500, 5000, 1000))) +
  theme(legend.title = element_blank(),
        axis.title.x = element_blank()) +
  facet_grid(basin ~ variable, scales = "free_x")
  

ggsave(here::here("output/profiles_total_changes.jpg"),
       width = 18,
       height = 10)



acidification_profiles %>%
  select(tref,
         basin,
         depth,
         MLR_basins,
         Version_ID_group,
         contains("_delta_interval")) %>%
  pivot_longer(contains("_delta_interval"),
               names_to = "variable",
               values_to = "delta_interval") %>%
  filter(tref != 1800,
         depth <= 3000) %>%
  mutate(variable = str_remove(variable, "_delta_interval")) %>% 
  ggplot(aes(
    delta_interval,
    depth,
    col = tref,
    group = interaction(tref, MLR_basins, Version_ID_group)
  )) +
  geom_vline(xintercept = 0) +
  geom_path() +
  scale_color_brewer(palette = "Set1", direction = -1) +
  labs(y = "Depth (m)",
       title = "Incremental change from previous estimate")+
  scale_y_continuous(trans = trans_reverser("sqrt"),
                     breaks = c(0, 100, 500, seq(1500, 5000, 1000))) +
  theme(legend.title = element_blank(),
        axis.title.x = element_blank()) +
  facet_grid(basin ~ variable, scales = "free_x")


ggsave(here::here("output/profiles_incremental_changes_all.jpg"),
       width = 18,
       height = 10)



acidification_profiles %>%
  select(tref,
         basin,
         depth,
         MLR_basins,
         Version_ID_group,
         contains("_delta_interval")) %>%
  pivot_longer(contains("_delta_interval"),
               names_to = "variable",
               values_to = "delta_interval") %>%
  filter(tref %in% c(2004,2014),
         depth <= 3000) %>%
  mutate(variable = str_remove(variable, "_delta_interval")) %>% 
  ggplot(aes(
    delta_interval,
    depth,
    col = tref,
    group = interaction(tref, MLR_basins, Version_ID_group)
  )) +
  geom_vline(xintercept = 0) +
  geom_path() +
  scale_color_brewer(palette = "Set1", direction = -1) +
  labs(y = "Depth (m)",
       title = "Incremental change from previous estimate")+
  scale_y_continuous(trans = trans_reverser("sqrt"),
                     breaks = c(0, 100, 500, seq(1500, 5000, 1000))) +
  theme(legend.title = element_blank(),
        axis.title.x = element_blank()) +
  facet_grid(basin ~ variable, scales = "free_x")



ggsave(here::here("output/profiles_incremental_changes_post_1994.jpg"),
       width = 18,
       height = 10)


```



# Write ouput

```{r write_output_files, eval=FALSE}

acidification_trend %>% 
  write_csv(paste0(path_OIA, "OIA.csv"))


acidification_layer %>% 
  write_csv(paste0(path_OIA, "OIA_layer.csv"))

acidification_zonal %>% 
  write_csv(paste0(path_OIA, "OIA_zonal.csv"))


acidification_global_section %>% 
  write_csv(paste0(path_OIA, "OIA_global_section.csv"))

acidification_profiles %>% 
  write_csv(paste0(path_OIA, "OIA_profiles.csv"))




```



