---
title: "OIA computation"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

# Libraries

```{r load_libraries_specific, include = FALSE}

library(stars)
library(seacarb)
library(tidync)

```

# Basinmask

```{r select_basinmask_5}

basinmask <- basinmask %>% 
  filter(MLR_basins == "5") %>% 
  select(lon, lat, basin)

```

# Path to files

```{r define_paths_to_access_eMLR_files, include = FALSE}

# path to eMLR estimates of delta Cant

path_observations <-
  paste0(path_root, "/observations/")

path_preprocessing    <-
  paste0(path_observations, "preprocessing/")

path_out <-   paste0(path_observations, "output_publication/")


# path to ocean interior temperature reconstructions

path_temperature <- 
  "/nfs/kryo/work/updata/cheng/CZ16_v3_IAP_Temperature_gridded_1month_netcdf/Monthly"

# path to OIA data generated for this study

path_OIA <-   "/nfs/kryo/work/jenmueller/ocean_interior_acidification/"


```

# Read data

## Delta Cant

```{r read_interior_dcant_files}

file_out <- paste0(path_out, "dcant_emlr_cstar_mueller_94-04-14.nc")

dcant_3d_read_mdim <-
  read_mdim(file_out)

ggplot() +
  geom_stars(data = dcant_3d_read_mdim %>% 
               filter(period == "1994 - 2004",
                      depth == 50)) +
  facet_grid(MLR_basins~Version_ID_group) +
  scale_fill_viridis_b(breaks = c(-Inf, seq(0,16,2), Inf),
                       na.value = "transparent")


dcant_3d_tibble <- dcant_3d_read_mdim %>% 
               # filter(Version_ID_group == "Standard case",
               #        MLR_basins == "3") %>% 
  as_tibble()

rm(dcant_3d_read_mdim, file_out)

dcant_3d_tibble <- dcant_3d_tibble %>% 
  drop_na()

# remove negative delta Cant
# dcant_3d_tibble <- dcant_3d_tibble
#   mutate(dcant = if_else(dcant < 0, 0, dcant))

dcant_3d_tibble %>%
  filter(depth == 500,
         Version_ID_group == "Standard case",
         MLR_basins == "3") %>%
  ggplot() +
  geom_raster(aes(lon, lat, fill = dcant)) +
  facet_grid(MLR_basins ~ Version_ID_group) +
  scale_fill_viridis_b(breaks = c(-Inf, seq(0, 16, 2), Inf),
                       na.value = "transparent")

```

## Total Cant 1994

```{r tcant_sabine_2004}

S04_cant_3d <-
  read_csv(paste(path_preprocessing,
                 "S04_tcant_3d.csv",
                 sep = ""))

# remove negative delta Cant
# S04_cant_3d <- S04_cant_3d %>%
#   mutate(tcant = if_else(tcant < 0, 0, tcant))

```


## GLODAP climatologies


```{r load_GLODAPv2_2016b_MappedClimatologies_interior_mapping}

variables <-
  c("TCO2", "TAlk", "PO4", "silicate", "NO3")

# i_variable <- variables[1]

for (i_variable in variables) {
  temp <- read_csv(paste(
    path_preprocessing,
    paste("GLODAPv2_2016_MappedClimatology_", i_variable, ".csv", sep = ""),
    sep = ""
  ))
  
  if (exists("GLODAP_predictors")) {
    GLODAP_predictors <- full_join(GLODAP_predictors, temp)
  }
  
  if (!exists("GLODAP_predictors")) {
    GLODAP_predictors <- temp
  }
}

rm(temp, i_variable, variables)

GLODAP_predictors <- GLODAP_predictors %>%
  rename(phosphate = PO4,
         nitrate = NO3,
         talk = TAlk,
         tco2 = TCO2)

# removed na's attributable to slightly different coverage of predictor fields
GLODAP_predictors <- GLODAP_predictors %>%
  drop_na()

```



## World Ocean Atlas 2018  

```{r load_WOA18}

WOA18_predictors <-
  read_csv(paste(path_preprocessing,
                 "WOA18_sal_temp.csv",
                 sep = ""))

WOA18_predictors_nuts_O2 <-
  read_csv(paste(path_preprocessing,
                 "WOA18_nuts_O2.csv",
                 sep = ""))

```


## Cheng temperature

```{r read_cheng_temperature}

# loop over reference years, plus/minus enveloppe years, and month
# to obtain a decadal averaged temperature field


for (i_tref in c(1994, 2004, 2014)) {
  # i_tref <- 1994
  print(i_tref)
  
  for (i_year in i_tref + seq(-1, 1, 1)) {
    # i_year <- i_tref + seq(-2,2,1)[1]
    print(i_year)
    
    for (i_month in c("01",
                      "02",
                      "03",
                      "04",
                      "05",
                      "06",
                      "07",
                      "08",
                      "09",
                      "10",
                      "11",
                      "12")) {
      # i_month <- "01"
      print(i_month)
      
      i_temperature_file <-
        paste0("CZ16_1_2000m_Temp_year_",
               i_year,
               "_month_",
               i_month,
               ".nc")
      print(i_temperature_file)
      
      tidy_df <-
        tidync(paste(path_temperature, i_temperature_file, sep = "/"))
      
      tibble_df <- tidy_df %>%
        hyper_tibble()
      
      tibble_df <-
        tibble_df %>%
        mutate(temp = if_else(temp == 999, NaN, temp))
      
      if (exists("temperature_year")) {
        temperature_year <- bind_rows(temperature_year, tibble_df)
      }
      
      if (!exists("temperature_year")) {
        temperature_year <- tibble_df
      }
      
    }
    
    temperature_year <- temperature_year %>%
      group_by(lat, lon, depth_std) %>%
      summarise(temp = mean(temp, na_rm = TRUE)) %>%
      ungroup()
    
    temperature_year <- temperature_year %>%
      mutate(year = i_year)
    
    if (exists("temperature_decade")) {
      temperature_decade <-
        bind_rows(temperature_decade, temperature_year)
    }
    
    if (!exists("temperature_decade")) {
      temperature_decade <- temperature_year
    }
    
    rm(temperature_year)
    
    
  }
  
  
  temperature_decade <- temperature_decade %>%
    group_by(lat, lon, depth_std) %>%
    summarise(temp = mean(temp, na_rm = TRUE)) %>%
    ungroup()
  
  temperature_decade <- temperature_decade %>%
    mutate(tref = i_tref)
  
  if (exists("temperature_all")) {
    temperature_all <-
      bind_rows(temperature_all, temperature_decade)
  }
  
  if (!exists("temperature_all")) {
    temperature_all <- temperature_decade
  }
  
  rm(temperature_decade)
  
}

rm(tibble_df,tidy_df, i_month, i_temperature_file, i_tref, i_year)

# rm(temperature_all)

temperature_all <-
  temperature_all %>%
  rename(depth = depth_std)

temperature_all %>%
  distinct(depth) %>% 
  pull

# change surface depth level from 1 to 0 for consistency with other data
temperature_all <-
  temperature_all %>%
  mutate(depth = if_else(depth == 1, 0, depth))

temperature_all %>%
  filter(depth == 500) %>%
  ggplot(aes(lon, lat, fill = temp)) +
  geom_tile() +
  scale_fill_viridis_c() +
  facet_wrap(~tref) +
  coord_quickmap()

# calculate decadal temperature change
temperature_all <- temperature_all %>%
  arrange(tref) %>%
  group_by(lon, lat, depth) %>%
  mutate(delta_temp = temp - first(temp)) %>%
  ungroup() %>% 
  filter(tref != 1994) %>% 
  select(lon, lat, depth, tref, delta_temp)


temperature_all %>%
  filter(depth == 500) %>%
  ggplot(aes(lon, lat, fill = delta_temp)) +
  geom_tile() +
  scale_fill_gradient2() +
  facet_wrap( ~ tref) +
  coord_quickmap()


```


# Join data

## WOA18 + GLODAP

WOA18 and GLODAP predictor climatologies are merged. Only horizontal grid cells with observations from both predictor fields are kept.

```{r join_WOA18_GLODAP_predictors}

# join deep water predictors

predictors <- right_join(GLODAP_predictors,
                          WOA18_predictors)

predictors <- rquery::natural_join(predictors, WOA18_predictors_nuts_O2,
                           by = c("lon", "lat", "depth", "basin_AIP"),
                           jointype = "LEFT") %>% 
  as_tibble()

predictors <- predictors %>% 
  drop_na()


rm(GLODAP_predictors, WOA18_predictors_nuts_O2, WOA18_predictors)

```

## Predictors + Cant

```{r join_predictors_dcant}

# predictors %>% distinct(depth) %>% pull()
# S04_cant_3d %>% distinct(depth) %>% pull()
# dcant_3d_tibble %>% distinct(depth) %>% pull()

DIC_1994 <- 
  inner_join(predictors,
             dcant_3d_tibble %>% filter(period == "1994 - 2004") %>% 
               select(-period))


DIC_1994 <- DIC_1994 %>% 
  mutate(tco2 = tco2 - 0.8 * dcant)

DIC_2004 <- DIC_1994 %>% 
  mutate(tco2 = tco2 + dcant)

DIC_2014 <-
  inner_join(DIC_2004 %>% select(-dcant),
             dcant_3d_tibble %>% filter(period == "2004 - 2014") %>%
               select(-period))

DIC_2014 <- DIC_2014 %>% 
  mutate(tco2 = tco2 + dcant)


DIC_1800 <- inner_join(
  DIC_1994 %>%   filter(Version_ID_group == "Standard case",
                        MLR_basins == "3"),
  S04_cant_3d %>% select(lon, lat, depth, tcant)
)

DIC_1800 <- DIC_1800 %>% 
  mutate(tco2 = tco2 - tcant)

DIC <- bind_rows(
  DIC_1800 %>% mutate(tref = "1800"),
  DIC_1994 %>% mutate(tref = "1994"),
  DIC_2004 %>% mutate(tref = "2004"),
  DIC_2014 %>% mutate(tref = "2014")
)

rm(DIC_1800, DIC_1994, DIC_2004, DIC_2014, predictors, dcant_3d_tibble, S04_cant_3d)

# create DIC fields with variable temperature

DIC_temp <- DIC %>%
  filter(tref %in% c(2004, 2014),
         Version_ID_group == "Standard case",
         MLR_basins == 3) %>%
  mutate(Version_ID_group = "Temperature")

DIC_temp %>%
  distinct(tref, Version_ID_group, MLR_basins)

DIC_depths <- DIC_temp %>% 
  distinct(depth) %>% 
  filter(depth <= 2000) %>% 
  pull()

# extend temperature field with DIC depth for interpolation
depth_grid <-
  expand_grid(
    temperature_all %>%
      distinct(lat, lon, tref),
    depth = DIC_depths
  )

temperature_all <-
  full_join(temperature_all,
            depth_grid)

rm(depth_grid)

temperature_all <-
  temperature_all %>%
  group_by(lon, lat, tref) %>%
  mutate(count_available = sum(!is.na(delta_temp))) %>% 
  ungroup()


temperature_all_surface <-
  temperature_all %>%
  filter(count_available == 1) %>%
  select(-count_available) %>%
  filter(!is.na(delta_temp))

temperature_all_int <-
  temperature_all %>%
  filter(count_available >= 2) %>% 
  select(-count_available) %>% 
  group_by(lon, lat, tref) %>%
  mutate(delta_temp = approxfun(depth, delta_temp, rule = 1)(depth)) %>%
  ungroup() %>% 
  filter(!is.na(delta_temp))

temperature_all <- bind_rows(
  temperature_all_surface,
  temperature_all_int
)

rm(
  temperature_all_surface,
  temperature_all_int
)

temperature_all <-
  temperature_all %>%
  filter(depth %in% DIC_depths)

temperature_all <- temperature_all %>% 
  mutate(tref = as.character(tref))

temperature_all <- temperature_all %>% 
  mutate(lon = lon - 0.5,
         lon = if_else(lon < 20, lon + 360, lon))

DIC_temp <- inner_join(
  DIC_temp,
  temperature_all)

DIC_temp <-
  DIC_temp %>%
  mutate(temp = temp + delta_temp) %>%
  select(-delta_temp)

DIC <- bind_rows(
  DIC,
  DIC_temp
)

rm(DIC_temp, temperature_all)

```

# Compute acidification trends

```{r compute_acidification_trends}

cases <- DIC %>%
  distinct(Version_ID_group, MLR_basins)


calc_delta_total <- function(x)
  (x - first(x))
calc_delta_interval <- function(x)
  (x - lag(x, default = first(x)))

for (i in 1:nrow(cases)) {
  # i <- 1
  
  i_Version_ID_group <-  cases[i, ]$Version_ID_group
  i_MLR_basins <-  cases[i, ]$MLR_basins
  
  i_DIC <- DIC %>%
    filter(Version_ID_group == i_Version_ID_group,
           MLR_basins == i_MLR_basins)
  
  
  acidification <- i_DIC %>%
    # filter(lon == 190.5,
    #        lat == 0.5,
    #        depth == 0) %>%
    mutate(
      sir(
        flag = 15,
        var1 = talk * 1e-6,
        var2 = tco2 * 1e-6,
        S = sal,
        T = temp,
        P = depth / 10,
        Pt = phosphate * 1e-6,
        Sit = silicate * 1e-6,
        k1k2 = "s20",
        kf = "dg",
        pHscale = "T"
      )
    )
  
  rm(i_DIC)
  
  acidification <- acidification %>%
    select(
      -c(
        dcant,
        tcant,
        flag,
        S,
        T,
        Patm,
        P,
        CO2,
        contains("fCO2"),
        contains("_t"),
        contains("_sws"),
        pH_free,
        HCO3,
        pCO2pot,
        pCO2,
        DIC,
        ALK
      )
    )
  
  acidification <- acidification %>%
    mutate(
      hyd_ion_calc = 10 ^ (-pH) * 1e6,
      CO3 = CO3 * 1e6,
      tco2_talk_ratio = tco2 / talk
    )
  
  if (i_Version_ID_group == "Temperature") {
    
    acidification_temp <- acidification %>%
      filter(tref %in% c(1800, 1994),
             Version_ID_group == "Standard case",
             MLR_basins == 3) %>%
      mutate(Version_ID_group = "Temperature")
    
    acidification <-
      bind_rows(acidification,
                acidification_temp)
    
    rm(acidification_temp)
    
  }
  
  
  acidification_trend <- acidification %>%
    arrange(tref) %>%
    group_by(lat, lon, depth, Version_ID_group, MLR_basins) %>%
    mutate(across(
      .cols = c(
        tco2,
        pH,
        pCO2insitu,
        CO3,
        OmegaAragonite,
        OmegaCalcite,
        hyd_ion_calc,
        tco2_talk_ratio,
        SIR,
        H_free,
        temp
      ),
      .fns = list(delta_total = calc_delta_total, delta_interval = calc_delta_interval)
    )) %>%
    ungroup()
  
  rm(acidification)
  
  
  acidification_trend %>%
    write_csv(paste0(path_OIA,"OIA_",i_Version_ID_group,"_",i_MLR_basins,".csv"))
  
  rm(acidification_trend)
  
}

```

# Compute buffer factors

```{r compute_buffer_factors}

for (i in 1:nrow(cases)) {
  # i <- 1
  
  i_Version_ID_group <-  cases[i,]$Version_ID_group
  i_MLR_basins <-  cases[i,]$MLR_basins
  
  
  i_DIC <- DIC %>%
    filter(Version_ID_group == i_Version_ID_group,
           MLR_basins == i_MLR_basins)
  
  buffer <- i_DIC %>%
    # filter(lon == 190.5,
    #        lat == 0.5,
    #        depth == 0) %>%
    mutate(
      buffesm(
        flag = 15,
        var1 = talk * 1e-6,
        var2 = tco2 * 1e-6,
        S = sal,
        T = temp,
        P = depth / 10,
        Pt = phosphate * 1e-6,
        Sit = silicate * 1e-6,
        k1k2 = "s20",
        kf = "dg",
        pHscale = "T"
      )
    )
  
  rm(i_DIC)
  
  buffer <- buffer %>%
    select(
      c(
        lon,
        lat,
        depth,
        tref,
        MLR_basins,
        Version_ID_group,
        gammaDIC,
        betaDIC,
        omegaDIC,
        R
      )
    )
  
    
  if (i_Version_ID_group == "Temperature") {
    
    buffer_temp <- buffer %>%
      filter(tref %in% c(1800, 1994),
             Version_ID_group == "Standard case",
             MLR_basins == 3) %>%
      mutate(Version_ID_group = "Temperature")
    
    buffer <-
      bind_rows(buffer,
                buffer_temp)
    
    rm(buffer_temp)
  }
  
  buffer_trend <- buffer %>%
    arrange(tref) %>%
    group_by(lat, lon, depth, Version_ID_group, MLR_basins) %>%
    mutate(across(
      .cols = c(gammaDIC,
                betaDIC,
                omegaDIC,
                R),
      .fns = list(delta_total = calc_delta_total, delta_interval = calc_delta_interval)
    )) %>%
    ungroup()
  
  rm(buffer)
  
  
  buffer_trend %>%
    write_csv(paste0(path_OIA,"buffer_",i_Version_ID_group,"_",i_MLR_basins,".csv"))
  
  rm(buffer_trend)
  
}


```



```{r write_output_files_stars, eval=FALSE}



# convert from tibble to stars object
acidification_trend_stars <- st_as_stars(
  acidification_trend,
  dims = c(
    "lon",
    "lat",
    "depth",
    "tref",
    "MLR_basins",
    "Version_ID_group"
  )
)

# assign coordinate system to horizontal (lon, lat) coordinates
# st_crs(dcant_inv_out_stars) <- "+proj=longlat"
st_crs(acidification_trend_stars) <- st_crs(4326)

# plot variable per depth level
# ggplot() +
#   geom_stars(data = acidification_trend_stars %>% 
#                filter(period == "1994 - 2004",
#                       depth == 50)) +
#   facet_grid(MLR_basins~Version_ID_group) +
#   scale_fill_viridis_b(breaks = c(-Inf, seq(0,16,2), Inf),
#                        na.value = "transparent")


file_out <- paste0(path_OIA, "OIA_pH.nc")

# write stars object to .nc file

names_OIA <-
  acidification_trend_stars %>%
  names()

acidification_trend_stars %>% 
  select(names_OIA[12]) %>% 
  write_mdim(file_out)

# # reopen .nc file with all available stars functions
# dcant_3d_read_ncdf <-
#   read_ncdf(file_out)
# dcant_3d_read_mdim <-
#   read_mdim(file_out)
# 
# # plot variable in object reopened
# 
# ggplot() +
#   geom_stars(data = dcant_3d_read_ncdf %>% 
#                filter(period == "1994 - 2004",
#                       depth == 50)) +
#   facet_grid(MLR_basins~Version_ID_group) +
#   scale_fill_viridis_b(breaks = c(-Inf, seq(0,16,2), Inf),
#                        na.value = "transparent")
# 
# ggplot() +
#   geom_stars(data = dcant_3d_read_mdim %>% 
#                filter(period == "1994 - 2004",
#                       depth == 50)) +
#   facet_grid(MLR_basins~Version_ID_group) +
#   scale_fill_viridis_b(breaks = c(-Inf, seq(0,16,2), Inf),
#                        na.value = "transparent")




```



